options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    recursion yes;
    dnssec-validation no;
    minimal-responses yes;
};

include "/etc/bind/named.conf.health";
include "/etc/bind/lab/named.conf.lab";
